---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-nfs
  namespace: kube-system
  labels:
    app: fake-nfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-nfs
  template:
    metadata:
      labels:
        app: fake-nfs
    spec:
      containers:
        - name: fake-nfs
          securityContext:
            privileged: true
          image: fake-nfsserver:0.1.0
          env:
            - name: NFS_EXPORT_0
              value: "/data/nfs_export *(rw,no_subtree_check)"
          volumeMounts:
            - mountPath: /data/nfs_export
              name: test-volume
      volumes:
        - name: test-volume
          hostPath:
            path: /data/nfs_export
            type: DirectoryOrCreate
